### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by knanahassouna1** [FACG5/News_Project#4]
Front End 
Relates  #2 
- [ ]  Make Input Field With Button for submit it in index.html 
- [ ]  Make Style of index.html.
- [ ] Make Error.html and Style it
- [ ] Make action listener  for submit button.
- [ ] Make  xhr request to sent query to server .
- [ ] make functoin to mainplate with resopne from xhr request.
